services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=certifai'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=root'
    ports:
      - "3306:3306"
